prop:
  upload-folder: /upload
server:
  port: 8082
  context-path: /
spring:
  http:
    multipart:
      max-file-size: 10Mb
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vueblog2
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.csy.blogServer.bean
logging:
  level:
     com.csy.blogServer.mapper: debug